Create openstackNetInit.sh
ITRI-ICL-K200/NFV-Orchestration-Demo-using-OAI-EPC pull request #12
Opened 2018-02-05 09:10 UTC by wy88yw

修改OpenStack初始的網路環境，包含刪除所有ipv6所需的動作

2018-02-05 09:15 UTC, ChunChiehWang commented on OpenBaton/openstackNetInit.sh
> +export OS_USERNAME=demo
read all 4 configurations from input argument instead of hard-coding it in the code

2018-02-05 09:32 UTC, yanghc commented on OpenBaton/openstackNetInit.sh
> +export OS_AUTH_URL=http://10.101.136.41:35357/v2.0
OpenStack 的  IP建議設為127.0.0.1 或是參數

2018-02-06 02:28 UTC, OaiTestBase commented on OpenBaton/openstackNetInit.sh
> +export OS_USERNAME=admin
建議將重複用到的字以變數取代:
export OS_USERNAME=admin和export OS_TENANT_NAME=admin中的admin
export OS_USERNAME=demo和export OS_TENANT_NAME=demo中的demo
對將來如果有需要修改內容時，
修改變數即可

2018-02-06 02:30 UTC, yanghc requested changes

2018-02-06 02:30 UTC, yanghc commented on OpenBaton/openstackNetInit.sh
> +neutron subnet-delete ipv6-public-subnet
少了設定DNS喔, 需將public network的DNS設為8.8.8.8

2018-02-06 06:18 UTC, wy88yw commented on OpenBaton/openstackNetInit.sh
> +export OS_AUTH_URL=http://10.101.136.41:35357/v2.0
已修正。

2018-02-06 06:37 UTC, wy88yw commented on OpenBaton/openstackNetInit.sh
> +export OS_USERNAME=demo
export 這四個環境變數目的在於分別登入project demo & admin，然後進行網路參數的修改，因為只能用在devstack all-in-one的OpenStack上，且需在OpenStack本機端執行，因此是否hard code就可以了。

2018-02-06 06:38 UTC, wy88yw commented on OpenBaton/openstackNetInit.sh
> +neutron subnet-delete ipv6-public-subnet
已修正。
# add dns in subnet "public-subnet"
neutron subnet-update public-subnet dns-nameserver 8.8.8.8

2018-02-06 07:17 UTC, yanghc approved these changes

2018-02-06 08:16 UTC, ChunChiehWang commented on OpenBaton/openstackNetInit.sh
> +export OS_USERNAME=demo
OK

2018-02-06 08:16 UTC, ChunChiehWang approved these changes

2018-02-06 09:05 UTC, OaiTestBase approved these changes

2018-02-07 02:52 UTC, merged